/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssistantsRouteImport } from './routes/assistants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssistantsIndexRouteImport } from './routes/assistants.index'
import { Route as AssistantsProfileIdRouteImport } from './routes/assistants.$profileId'
import { Route as AssistantsProfileIdProfileRouteImport } from './routes/assistants.$profileId.profile'
import { Route as AssistantsProfileIdIntegrationsRouteImport } from './routes/assistants.$profileId.integrations'
import { Route as AssistantsProfileIdApprovalsRouteImport } from './routes/assistants.$profileId.approvals'
import { Route as AssistantsProfileIdBrowserHandoffHandoffIdRouteImport } from './routes/assistants.$profileId.browser-handoff.$handoffId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsRoute = AssistantsRouteImport.update({
  id: '/assistants',
  path: '/assistants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantsIndexRoute = AssistantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsProfileIdRoute = AssistantsProfileIdRouteImport.update({
  id: '/$profileId',
  path: '/$profileId',
  getParentRoute: () => AssistantsRoute,
} as any)
const AssistantsProfileIdProfileRoute =
  AssistantsProfileIdProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AssistantsProfileIdRoute,
  } as any)
const AssistantsProfileIdIntegrationsRoute =
  AssistantsProfileIdIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AssistantsProfileIdRoute,
  } as any)
const AssistantsProfileIdApprovalsRoute =
  AssistantsProfileIdApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AssistantsProfileIdRoute,
  } as any)
const AssistantsProfileIdBrowserHandoffHandoffIdRoute =
  AssistantsProfileIdBrowserHandoffHandoffIdRouteImport.update({
    id: '/browser-handoff/$handoffId',
    path: '/browser-handoff/$handoffId',
    getParentRoute: () => AssistantsProfileIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistants': typeof AssistantsRouteWithChildren
  '/login': typeof LoginRoute
  '/assistants/$profileId': typeof AssistantsProfileIdRouteWithChildren
  '/assistants/': typeof AssistantsIndexRoute
  '/assistants/$profileId/approvals': typeof AssistantsProfileIdApprovalsRoute
  '/assistants/$profileId/integrations': typeof AssistantsProfileIdIntegrationsRoute
  '/assistants/$profileId/profile': typeof AssistantsProfileIdProfileRoute
  '/assistants/$profileId/browser-handoff/$handoffId': typeof AssistantsProfileIdBrowserHandoffHandoffIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assistants/$profileId': typeof AssistantsProfileIdRouteWithChildren
  '/assistants': typeof AssistantsIndexRoute
  '/assistants/$profileId/approvals': typeof AssistantsProfileIdApprovalsRoute
  '/assistants/$profileId/integrations': typeof AssistantsProfileIdIntegrationsRoute
  '/assistants/$profileId/profile': typeof AssistantsProfileIdProfileRoute
  '/assistants/$profileId/browser-handoff/$handoffId': typeof AssistantsProfileIdBrowserHandoffHandoffIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistants': typeof AssistantsRouteWithChildren
  '/login': typeof LoginRoute
  '/assistants/$profileId': typeof AssistantsProfileIdRouteWithChildren
  '/assistants/': typeof AssistantsIndexRoute
  '/assistants/$profileId/approvals': typeof AssistantsProfileIdApprovalsRoute
  '/assistants/$profileId/integrations': typeof AssistantsProfileIdIntegrationsRoute
  '/assistants/$profileId/profile': typeof AssistantsProfileIdProfileRoute
  '/assistants/$profileId/browser-handoff/$handoffId': typeof AssistantsProfileIdBrowserHandoffHandoffIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistants'
    | '/login'
    | '/assistants/$profileId'
    | '/assistants/'
    | '/assistants/$profileId/approvals'
    | '/assistants/$profileId/integrations'
    | '/assistants/$profileId/profile'
    | '/assistants/$profileId/browser-handoff/$handoffId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assistants/$profileId'
    | '/assistants'
    | '/assistants/$profileId/approvals'
    | '/assistants/$profileId/integrations'
    | '/assistants/$profileId/profile'
    | '/assistants/$profileId/browser-handoff/$handoffId'
  id:
    | '__root__'
    | '/'
    | '/assistants'
    | '/login'
    | '/assistants/$profileId'
    | '/assistants/'
    | '/assistants/$profileId/approvals'
    | '/assistants/$profileId/integrations'
    | '/assistants/$profileId/profile'
    | '/assistants/$profileId/browser-handoff/$handoffId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantsRoute: typeof AssistantsRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants': {
      id: '/assistants'
      path: '/assistants'
      fullPath: '/assistants'
      preLoaderRoute: typeof AssistantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistants/': {
      id: '/assistants/'
      path: '/'
      fullPath: '/assistants/'
      preLoaderRoute: typeof AssistantsIndexRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/$profileId': {
      id: '/assistants/$profileId'
      path: '/$profileId'
      fullPath: '/assistants/$profileId'
      preLoaderRoute: typeof AssistantsProfileIdRouteImport
      parentRoute: typeof AssistantsRoute
    }
    '/assistants/$profileId/profile': {
      id: '/assistants/$profileId/profile'
      path: '/profile'
      fullPath: '/assistants/$profileId/profile'
      preLoaderRoute: typeof AssistantsProfileIdProfileRouteImport
      parentRoute: typeof AssistantsProfileIdRoute
    }
    '/assistants/$profileId/integrations': {
      id: '/assistants/$profileId/integrations'
      path: '/integrations'
      fullPath: '/assistants/$profileId/integrations'
      preLoaderRoute: typeof AssistantsProfileIdIntegrationsRouteImport
      parentRoute: typeof AssistantsProfileIdRoute
    }
    '/assistants/$profileId/approvals': {
      id: '/assistants/$profileId/approvals'
      path: '/approvals'
      fullPath: '/assistants/$profileId/approvals'
      preLoaderRoute: typeof AssistantsProfileIdApprovalsRouteImport
      parentRoute: typeof AssistantsProfileIdRoute
    }
    '/assistants/$profileId/browser-handoff/$handoffId': {
      id: '/assistants/$profileId/browser-handoff/$handoffId'
      path: '/browser-handoff/$handoffId'
      fullPath: '/assistants/$profileId/browser-handoff/$handoffId'
      preLoaderRoute: typeof AssistantsProfileIdBrowserHandoffHandoffIdRouteImport
      parentRoute: typeof AssistantsProfileIdRoute
    }
  }
}

interface AssistantsProfileIdRouteChildren {
  AssistantsProfileIdApprovalsRoute: typeof AssistantsProfileIdApprovalsRoute
  AssistantsProfileIdIntegrationsRoute: typeof AssistantsProfileIdIntegrationsRoute
  AssistantsProfileIdProfileRoute: typeof AssistantsProfileIdProfileRoute
  AssistantsProfileIdBrowserHandoffHandoffIdRoute: typeof AssistantsProfileIdBrowserHandoffHandoffIdRoute
}

const AssistantsProfileIdRouteChildren: AssistantsProfileIdRouteChildren = {
  AssistantsProfileIdApprovalsRoute: AssistantsProfileIdApprovalsRoute,
  AssistantsProfileIdIntegrationsRoute: AssistantsProfileIdIntegrationsRoute,
  AssistantsProfileIdProfileRoute: AssistantsProfileIdProfileRoute,
  AssistantsProfileIdBrowserHandoffHandoffIdRoute:
    AssistantsProfileIdBrowserHandoffHandoffIdRoute,
}

const AssistantsProfileIdRouteWithChildren =
  AssistantsProfileIdRoute._addFileChildren(AssistantsProfileIdRouteChildren)

interface AssistantsRouteChildren {
  AssistantsProfileIdRoute: typeof AssistantsProfileIdRouteWithChildren
  AssistantsIndexRoute: typeof AssistantsIndexRoute
}

const AssistantsRouteChildren: AssistantsRouteChildren = {
  AssistantsProfileIdRoute: AssistantsProfileIdRouteWithChildren,
  AssistantsIndexRoute: AssistantsIndexRoute,
}

const AssistantsRouteWithChildren = AssistantsRoute._addFileChildren(
  AssistantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantsRoute: AssistantsRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
