export {
  BOLDSIGN_SIGNATURE_WEBHOOK_ADAPTER_KEY,
  BOLDSIGN_WEBHOOK_EVENT_SCOPE,
  BOLDSIGN_WEBHOOK_PROVIDER_KEY,
  BOLDSIGN_WEBHOOK_RESOURCE_TYPE,
} from "../../capabilities/boldsign/webhook-types";
