import {
  defineReadTool,
  defineWriteTool,
  readToolDescription,
  toolOutputProperty,
  type ToolContract,
  writeToolDescription,
} from "@ai-assistants/tool-contracts";
import {
  microsoftOnedriveDriveGetInputSchema,
  microsoftOnedriveDrivesListInputSchema,
  microsoftOnedriveFileSaveInputSchema,
  microsoftOnedriveFilesSearchInputSchema,
  microsoftOnedriveFolderChildrenListInputSchema,
  microsoftOnedriveFolderCreateInputSchema,
  microsoftOnedriveGetItemInputSchema,
  microsoftOnedriveInviteRecipientsInputSchema,
  microsoftOnedriveItemCopyInputSchema,
  microsoftOnedriveItemDeleteInputSchema,
  microsoftOnedriveItemMoveInputSchema,
  microsoftOnedriveItemUpdateInputSchema,
  microsoftOnedrivePermissionDeleteInputSchema,
  microsoftOnedrivePermissionGetInputSchema,
  microsoftOnedrivePermissionsListInputSchema,
  microsoftOnedriveRecentItemsListInputSchema,
  microsoftOnedriveSharingLinkCreateInputSchema,
  microsoftOnedriveSharedItemsListInputSchema,
  microsoftOnedriveSmallFileUploadInputSchema,
  microsoftOnedriveVersionsListInputSchema,
  microsoftOnedriveAccountsListInputSchema,
  microsoftOnedriveAccountsListOutputSchema,
  microsoftOnedriveExternalWriteOutputSchema,
  microsoftOnedriveFileSaveOutputSchema,
  microsoftOnedriveDrivesOutputSchema,
  microsoftOnedriveItemOutputSchema,
  microsoftOnedriveItemsOutputSchema,
  microsoftOnedrivePermissionOutputSchema,
  microsoftOnedrivePermissionsOutputSchema,
} from "./schemas";

export const MICROSOFT_ONEDRIVE_PLUGIN_ID = "microsoft-onedrive-tools";

export const microsoftOnedriveToolContracts = [
  defineReadTool({
    name: "microsoft_onedrive_accounts_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List OneDrive capability instances",
    description: readToolDescription({
      useWhen: "the agent needs configured OneDrive account choices for this profile",
      operation: "Lists connected OneDrive accounts and current health without fetching files",
      returns: "OneDrive account metadata for choosing connectedAccountId",
      notes: ["Use when multiple OneDrive accounts may exist"],
    }),
    inputSchema: microsoftOnedriveAccountsListInputSchema,
    outputSchema: microsoftOnedriveAccountsListOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_drives_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List OneDrive drives",
    description: readToolDescription({
      useWhen: "the agent needs OneDrive drive metadata for account or default-drive context",
      operation: "Lists OneDrive drives available to the connected account",
      returns: "OneDrive drive ids, names, and metadata",
      notes: [
        "This surface's browse, search, and write tools operate on the connected account's default OneDrive drive.",
      ],
    }),
    inputSchema: microsoftOnedriveDrivesListInputSchema,
    outputSchema: microsoftOnedriveDrivesOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_drive_get",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Get default OneDrive",
    description: readToolDescription({
      useWhen: "root or default OneDrive drive identity is needed for browsing or file operations",
      operation: "Gets the signed-in user's default OneDrive drive",
      returns: "default OneDrive drive metadata",
    }),
    inputSchema: microsoftOnedriveDriveGetInputSchema,
    outputSchema: microsoftOnedriveItemOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_folder_children_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List OneDrive folder children",
    description: readToolDescription({
      useWhen: "the user needs to browse a known OneDrive folder location",
      operation: "Lists children under a OneDrive folder",
      returns: "OneDrive item metadata and pagination details",
      doNotUse: "the user needs item search; use microsoft_onedrive_files_search instead",
      notes: ["Omit itemId or use root for the drive root"],
    }),
    inputSchema: microsoftOnedriveFolderChildrenListInputSchema,
    outputSchema: microsoftOnedriveItemsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_recent_items_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List recent OneDrive items",
    description: readToolDescription({
      useWhen: "the user refers to a recent OneDrive file but the exact location or id is unknown",
      operation: "Lists recently used OneDrive items",
      returns: "recent OneDrive item metadata",
    }),
    inputSchema: microsoftOnedriveRecentItemsListInputSchema,
    outputSchema: microsoftOnedriveItemsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_files_search",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Search OneDrive items",
    description: readToolDescription({
      useWhen:
        "OneDrive item ids are unknown before metadata, download, move, share, or delete actions",
      operation: "Searches OneDrive items by query string",
      returns: "matching OneDrive item metadata",
    }),
    inputSchema: microsoftOnedriveFilesSearchInputSchema,
    outputSchema: microsoftOnedriveItemsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_shared_items_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List shared OneDrive items",
    description: readToolDescription({
      useWhen: "the user asks about OneDrive files shared with them rather than files they own",
      operation: "Lists OneDrive items shared with the user",
      returns: "shared OneDrive item metadata",
    }),
    inputSchema: microsoftOnedriveSharedItemsListInputSchema,
    outputSchema: microsoftOnedriveItemsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_item_get",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Get OneDrive item",
    description: readToolDescription({
      useWhen: "OneDrive item metadata must be confirmed before save or mutation",
      operation: "Gets a OneDrive item by id or path",
      returns: "OneDrive item metadata",
      notes: ["Provide exactly one of itemId or itemPath, not both"],
    }),
    inputSchema: microsoftOnedriveGetItemInputSchema,
    outputSchema: microsoftOnedriveItemOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_versions_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List OneDrive file versions",
    description: readToolDescription({
      useWhen: "the user asks about version history or a historical file state must be chosen",
      operation: "Lists versions for a OneDrive file",
      returns: "OneDrive file version metadata",
    }),
    inputSchema: microsoftOnedriveVersionsListInputSchema,
    outputSchema: microsoftOnedriveItemsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_permissions_list",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "List OneDrive item permissions",
    description: readToolDescription({
      useWhen: "the user needs to confirm who has access before sharing changes",
      operation: "Lists permissions on a OneDrive item",
      returns: "OneDrive permission ids, roles, grantees, and metadata",
    }),
    inputSchema: microsoftOnedrivePermissionsListInputSchema,
    outputSchema: microsoftOnedrivePermissionsOutputSchema,
  }),
  defineReadTool({
    name: "microsoft_onedrive_permission_get",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Get OneDrive permission",
    description: readToolDescription({
      useWhen: "exact OneDrive permission role or grantee metadata is needed",
      operation: "Gets one OneDrive item permission by permission id",
      returns: "the selected OneDrive permission's role, grantee, and metadata",
    }),
    inputSchema: microsoftOnedrivePermissionGetInputSchema,
    outputSchema: microsoftOnedrivePermissionOutputSchema,
  }),
  defineWriteTool({
    name: "microsoft_onedrive_file_save",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Save OneDrive file to artifact",
    description: writeToolDescription({
      useWhen: "a OneDrive file must be delivered later or passed to another tool as an artifact",
      operation: "Downloads OneDrive file bytes and stores them as a bounded profile file",
      returns: "saved artifact metadata and safe failure details",
      notes: ["If filename is omitted, the artifact filename is derived from provider metadata"],
      sideEffect:
        "creates an internal durable profile file; it does not mutate OneDrive or send the file by itself",
      safety: "the source OneDrive file must identify the intended file",
    }),
    inputSchema: microsoftOnedriveFileSaveInputSchema,
    outputSchema: microsoftOnedriveFileSaveOutputSchema,
  }),
  defineWriteTool({
    name: "microsoft_onedrive_folder_create",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Create OneDrive folder",
    description: writeToolDescription({
      useWhen: "the user wants to create a OneDrive folder",
      operation: "Creates a folder in OneDrive",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: ["Use parentItemId=root only when the drive root is intended"],
      sideEffect: "may create a OneDrive folder or create an approval-governed OneDrive action",
      safety: "the folder name and parent/root destination must be clear",
    }),
    inputSchema: microsoftOnedriveFolderCreateInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.folder.create",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_item_update",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Update OneDrive item",
    description: writeToolDescription({
      useWhen: "the user wants to update OneDrive item metadata",
      operation: "Updates metadata fields on one OneDrive item",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Prefer microsoft_onedrive_item_move for ordinary filesystem move or rename requests; use this for metadata patches such as description or fileSystemInfo",
      ],
      sideEffect:
        "may update OneDrive item metadata or create an approval-governed OneDrive action",
      safety:
        "the exact item and at least one actual metadata field such as name, description, fileSystemInfo, or parentReference must be clear; itemId alone is not useful",
    }),
    inputSchema: microsoftOnedriveItemUpdateInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.item.update",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_item_move",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Move or rename OneDrive item",
    description: writeToolDescription({
      useWhen: "the user wants to move or rename a OneDrive item",
      operation: "Moves a OneDrive item, renames it, or does both in one provider action",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Provide parentFolderId to move, name to rename, or both",
        "Prefer this tool for ordinary filesystem move or rename requests instead of microsoft_onedrive_item_update",
      ],
      sideEffect:
        "may move or rename a OneDrive item or create an approval-governed OneDrive action",
      safety:
        "the exact item and destination folder and/or new name must be clear; itemId alone is not useful",
    }),
    inputSchema: microsoftOnedriveItemMoveInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.item.move",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_item_copy",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Copy OneDrive item",
    description: writeToolDescription({
      useWhen: "the user wants to copy a OneDrive item",
      operation: "Copies one OneDrive item into a target parent folder, optionally with a new name",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may create a OneDrive item copy or create an approval-governed OneDrive action",
      safety: "the source item and target parent folder must be clear",
    }),
    inputSchema: microsoftOnedriveItemCopyInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.item.copy",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_item_delete",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Delete OneDrive item",
    description: writeToolDescription({
      useWhen: "the user wants to delete a OneDrive item",
      operation: "Deletes one OneDrive item using provider delete semantics",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may delete a OneDrive item or create an approval-governed OneDrive action",
      safety: "the exact item must be confirmed because this is a destructive external write",
    }),
    inputSchema: microsoftOnedriveItemDeleteInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.item.delete",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_small_file_upload",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Upload small OneDrive file",
    description: writeToolDescription({
      useWhen: "small base64 content or an existing profile file must be uploaded to OneDrive",
      operation:
        "Uploads direct base64 content or profile file bytes to OneDrive using the simple single-request upload path",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: ["Use source.kind=profile_file for assistant-created or provider-saved files"],
      doNotUse:
        "large or resumable uploads are required; this surface only supports simple small-file uploads",
      sideEffect: "may create a OneDrive file or create an approval-governed OneDrive action",
      safety: "the filename, source file/content, destination, and content type must be clear",
    }),
    inputSchema: microsoftOnedriveSmallFileUploadInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.file.upload",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_sharing_link_create",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Create OneDrive sharing link",
    description: writeToolDescription({
      useWhen: "the user wants to create a OneDrive sharing link",
      operation: "Creates a sharing link for one OneDrive item",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Use type/scope to control view/edit/embed and anonymous/organization access; choose scope deliberately, and omit it only when the provider default is intended",
      ],
      sideEffect: "may grant link-based access or create an approval-governed OneDrive action",
      safety:
        "the exact item, link type, and chosen or intentionally omitted access scope must be clear",
    }),
    inputSchema: microsoftOnedriveSharingLinkCreateInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.sharing_link.create",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_invite_recipients",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Invite OneDrive recipients",
    description: writeToolDescription({
      useWhen: "the user wants to invite recipients to a OneDrive item",
      operation: "Invites recipients to a OneDrive item with selected roles",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Each recipient must include email, objectId, or alias; roles controls read/write access",
      ],
      sideEffect:
        "may grant recipient access and notify invitees or create an approval-governed OneDrive action",
      safety: "the exact item, recipients, roles, and notification intent must be clear",
    }),
    inputSchema: microsoftOnedriveInviteRecipientsInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.invitation.send",
  }),
  defineWriteTool({
    name: "microsoft_onedrive_permission_delete",
    pluginId: MICROSOFT_ONEDRIVE_PLUGIN_ID,
    label: "Delete OneDrive permission",
    description: writeToolDescription({
      useWhen: "the user wants to remove a OneDrive permission",
      operation: "Deletes one OneDrive item permission",
      returns: `the ${toolOutputProperty(microsoftOnedriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may revoke OneDrive item access or create an approval-governed OneDrive action",
      safety: "the exact permission id and item must be confirmed because access can be revoked",
    }),
    inputSchema: microsoftOnedrivePermissionDeleteInputSchema,
    outputSchema: microsoftOnedriveExternalWriteOutputSchema,
    externalAction: "microsoft_onedrive.permission.delete",
  }),
] as const satisfies readonly ToolContract[];

export type MicrosoftOnedriveToolName = (typeof microsoftOnedriveToolContracts)[number]["name"];
