import {
  defineReadTool,
  defineWriteTool,
  readToolDescription,
  toolOutputProperty,
  type ToolContract,
  writeToolDescription,
} from "@ai-assistants/tool-contracts";
import {
  googleDriveFileCopyInputSchema,
  googleDriveFileDeleteInputSchema,
  googleDriveFileGetInputSchema,
  googleDriveFileMoveInputSchema,
  googleDriveFileRenameInputSchema,
  googleDriveFileRestoreInputSchema,
  googleDriveFileSaveInputSchema,
  googleDriveFileShareInputSchema,
  googleDriveFileTrashInputSchema,
  googleDriveFileUpdateDescriptionInputSchema,
  googleDriveFileUploadInputSchema,
  googleDriveFolderListInputSchema,
  googleDriveFolderCreateInputSchema,
  googleDrivePermissionDeleteInputSchema,
  googleDrivePermissionGetInputSchema,
  googleDrivePermissionsListInputSchema,
  googleDrivePermissionUpdateInputSchema,
  googleDriveSearchInputSchema,
  googleDriveAccountsListInputSchema,
  googleDriveSharedDrivesListInputSchema,
  googleDriveExternalWriteOutputSchema,
  googleDriveFileOutputSchema,
  googleDriveFilesOutputSchema,
  googleDriveFileSaveOutputSchema,
  googleDrivePermissionOutputSchema,
  googleDrivePermissionsOutputSchema,
  googleDriveAccountsListOutputSchema,
  googleDriveSharedDrivesOutputSchema,
} from "./schemas";

export const GOOGLE_DRIVE_PLUGIN_ID = "google-drive-tools";

export const googleDriveToolContracts = [
  defineReadTool({
    name: "google_drive_folder_list",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "List folder children",
    description: readToolDescription({
      useWhen: "the user needs to browse a known Google Drive folder location",
      operation:
        "Lists immediate children for a Google Drive folder, or the My Drive root when no folder is provided",
      returns: "Drive file and folder metadata plus pagination details",
      doNotUse: "the user needs full-drive search; use google_drive_search instead",
      notes: [
        "Set includeSharedDrives when shared-drive folder contents should be included",
        "Only returned child file entries prove the folder contains files. A folder metadata match from search does not prove folder contents.",
      ],
    }),
    inputSchema: googleDriveFolderListInputSchema,
    outputSchema: googleDriveFilesOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_accounts_list",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "List Drive Accounts",
    description: readToolDescription({
      useWhen: "the agent needs configured Google Drive account choices for this profile",
      operation:
        "Lists enabled Google Drive capability instances, including labels and connection health, without calling the provider",
      returns: "Drive account metadata for choosing connectedAccountId",
      notes: ["Use this before Drive reads or writes when multiple Drive accounts may exist"],
    }),
    inputSchema: googleDriveAccountsListInputSchema,
    outputSchema: googleDriveAccountsListOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_search",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Search Drive files",
    description: readToolDescription({
      useWhen: "the user needs to search or list Google Drive files from current Drive data",
      operation: "Searches Drive files using plain-language query or advanced Drive q syntax",
      returns: "matching Drive file metadata and pagination details",
      notes: [
        "Callers must supply query or driveQuery",
        "Use query for plain-language search, driveQuery for advanced Drive q syntax, and pageSize/cursor for pagination",
        "This tool has no folderId input; use google_drive_folder_list to list children of a known folder.",
        "Use driveQuery with `sharedWithMe and trashed = false` to find files or folders shared with the connected Google account",
        "A matching folder result only proves the folder exists. Do not say it contains supporting files, completed documents, filed records, or deal evidence unless a folder listing or file-targeted search returns those file entries.",
        "An empty folder or empty search result only proves no matching files were found in that searched Drive scope. It is not evidence of a required-document checklist.",
        "Only report specific missing required documents when another current source defines the requirements, such as CRM file/link columns, checklist subitems, a named template, or an explicit user-provided checklist.",
        "If no current requirement source is found, say the requirement source is missing; report present/absent Drive and CRM evidence without inventing standard required documents.",
      ],
    }),
    inputSchema: googleDriveSearchInputSchema,
    outputSchema: googleDriveFilesOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_file_get",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Get file metadata",
    description: readToolDescription({
      useWhen: "current metadata for one Google Drive file is needed before download or mutation",
      operation: "Fetches one Google Drive file's current metadata",
      returns: "name, MIME type, parents, links, state, and other Drive file metadata",
    }),
    inputSchema: googleDriveFileGetInputSchema,
    outputSchema: googleDriveFileOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_shared_drives_list",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "List shared drives",
    description: readToolDescription({
      useWhen: "the agent needs shared-drive ids before browsing or searching shared-drive content",
      operation: "Lists shared drives available to the connected Google Drive account",
      returns: "shared-drive ids, names, and metadata",
    }),
    inputSchema: googleDriveSharedDrivesListInputSchema,
    outputSchema: googleDriveSharedDrivesOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_permissions_list",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "List file permissions",
    description: readToolDescription({
      useWhen: "the user needs to confirm who has access before sharing changes",
      operation: "Lists permissions on a Google Drive file or shared drive",
      returns: "permission ids, roles, grantees, and permission metadata",
    }),
    inputSchema: googleDrivePermissionsListInputSchema,
    outputSchema: googleDrivePermissionsOutputSchema,
  }),
  defineReadTool({
    name: "google_drive_permission_get",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Get permission",
    description: readToolDescription({
      useWhen: "exact role, grantee, or permission metadata is needed",
      operation: "Gets one Google Drive file permission by permission id",
      returns: "the selected permission's role, grantee, and metadata",
    }),
    inputSchema: googleDrivePermissionGetInputSchema,
    outputSchema: googleDrivePermissionOutputSchema,
  }),
  defineWriteTool({
    name: "google_drive_file_save",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Save Drive file to artifact",
    description: writeToolDescription({
      useWhen:
        "a Google Drive file must be delivered later or passed to another tool as an artifact",
      operation:
        "Downloads or exports Google Drive file bytes and stores them as a bounded profile file for later delivery or tool handoff",
      returns: "saved artifact metadata and safe failure details",
      notes: [
        "Use fileId for the Google Drive file id; do not pass id.",
        "Use mode=media for binary files and mode=export with exportMimeType for Google Docs/Sheets/Slides",
        "When mode=export, provide filename with the intended extension, such as Proposal.pdf or Sheet.xlsx",
        "This is an internal read/delivery handoff. If saved file analysis conflicts with live provider evidence or fails extraction, do not fall back to profile files as a source of truth for the current provider file.",
      ],
      sideEffect:
        "creates an internal durable profile file; it does not mutate Drive or send the file by itself",
      safety: "the source file id and export mode must match the intended file",
    }),
    inputSchema: googleDriveFileSaveInputSchema,
    outputSchema: googleDriveFileSaveOutputSchema,
  }),
  defineWriteTool({
    name: "google_drive_folder_create",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Create Drive folder",
    description: writeToolDescription({
      useWhen: "the user wants to create a Google Drive folder",
      operation: "Creates a folder in Google Drive",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Use parentId to create inside a known folder; omit parentId only when the Drive root is intended",
      ],
      sideEffect: "may create a Drive folder or create an approval-governed Drive action",
      safety: "the folder name and parent/root destination must be clear",
    }),
    inputSchema: googleDriveFolderCreateInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.folder.create",
  }),
  defineWriteTool({
    name: "google_drive_file_rename",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Rename Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to rename an existing Google Drive file",
      operation: "Changes only the file metadata name; it does not move the file between folders",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      doNotUse: "the user wants to change parent folders; use google_drive_file_move instead",
      sideEffect: "may rename a Drive file or create an approval-governed Drive action",
      safety: "the exact file id and new name must be clear",
    }),
    inputSchema: googleDriveFileRenameInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.rename",
  }),
  defineWriteTool({
    name: "google_drive_file_update_description",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Update Drive file description",
    description: writeToolDescription({
      useWhen: "the user wants to update a Google Drive file description",
      operation: "Changes only the file description metadata, not document contents",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may update Drive file metadata or create an approval-governed Drive action",
      safety: "the exact file id and new description must be clear",
    }),
    inputSchema: googleDriveFileUpdateDescriptionInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.update_description",
  }),
  defineWriteTool({
    name: "google_drive_file_move",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Move Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to move a Google Drive file between parent folders",
      operation:
        "Moves one Drive file from its current parent folder to a destination parent folder",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may move a Drive file or create an approval-governed Drive action",
      safety:
        "both current and destination parent folder ids must be clear to avoid moving the wrong file. If multiple plausible destination folders match the client/deal, ask which one to use before moving.",
    }),
    inputSchema: googleDriveFileMoveInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.move",
  }),
  defineWriteTool({
    name: "google_drive_file_copy",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Copy Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to copy a Google Drive file",
      operation:
        "Copies one Drive file, optionally renaming the copy or placing it in a destination folder",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may create a Drive file copy or create an approval-governed Drive action",
      safety:
        "the source file and optional destination/name must be clear. If multiple plausible destination folders match the client/deal, ask which one to use before copying.",
    }),
    inputSchema: googleDriveFileCopyInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.copy",
  }),
  defineWriteTool({
    name: "google_drive_file_upload",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Upload Drive file",
    description: writeToolDescription({
      useWhen:
        "small direct content or an existing profile file must be uploaded to Google Drive",
      operation: "Uploads direct content or profile file bytes to Google Drive",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Use top-level name for the Drive filename; do not pass filename.",
        "Use source.kind=profile_file for assistant-created or provider-saved files.",
        "When uploading an artifact and a MIME type override is needed, put mimeType inside source; do not pass top-level mimeType.",
        "Use source.kind=direct_content for small explicit text/base64 bytes; folderId sets the destination folder and omitting it uses the provider default/root",
      ],
      doNotUse:
        "content cannot fit safely in a single provider upload or requires a resumable upload path; no resumable Drive upload tool is exposed here",
      sideEffect: "may create a Drive file or create an approval-governed Drive action",
      safety:
        "the filename, source file/content, MIME type, and destination folder/root intent must be clear. If multiple plausible destination folders match the client/deal, ask which one to use before uploading.",
    }),
    inputSchema: googleDriveFileUploadInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.upload",
  }),
  defineWriteTool({
    name: "google_drive_file_trash",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Trash Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to move a Google Drive file to trash",
      operation: "Moves one Drive file to trash",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: ["This is reversible through restore when provider state still allows it"],
      sideEffect: "may trash a Drive file or create an approval-governed Drive action",
      safety: "the exact file must be confirmed because this is a destructive provider write",
    }),
    inputSchema: googleDriveFileTrashInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.trash",
  }),
  defineWriteTool({
    name: "google_drive_file_restore",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Restore Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to restore a trashed Google Drive file",
      operation: "Restores one trashed Drive file",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      doNotUse: "the file is not currently in trash",
      sideEffect: "may restore a Drive file or create an approval-governed Drive action",
      safety: "the exact trashed file must be clear",
    }),
    inputSchema: googleDriveFileRestoreInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.restore",
  }),
  defineWriteTool({
    name: "google_drive_file_delete",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Delete Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to permanently delete a Google Drive file",
      operation: "Permanently deletes one Drive file",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      doNotUse: "the user wants reversible removal; use google_drive_file_trash instead",
      sideEffect: "may permanently delete a Drive file or create an approval-governed Drive action",
      safety:
        "the exact file must be confirmed because this is destructive and not the same as trash",
    }),
    inputSchema: googleDriveFileDeleteInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.delete",
  }),
  defineWriteTool({
    name: "google_drive_file_share",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Share Drive file",
    description: writeToolDescription({
      useWhen: "the user wants to share a Google Drive file",
      operation: "Creates a Drive permission for a user, group, domain, or anyone share",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "user/group shares require emailAddress; domain shares require domain; anyone shares do not use either",
        "role=owner transfers ownership; use it only when the user explicitly wants ownership transfer, not merely edit access",
      ],
      sideEffect: "may grant Drive file access or create an approval-governed Drive action",
      safety: "the exact file, grantee/scope, and role must be clear",
    }),
    inputSchema: googleDriveFileShareInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.file.share",
  }),
  defineWriteTool({
    name: "google_drive_permission_update",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Update Drive permission",
    description: writeToolDescription({
      useWhen: "the user wants to update an existing Google Drive permission role",
      operation: "Updates one existing Drive permission role",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      notes: [
        "Use permission ids from google_drive_permissions_list or google_drive_permission_get",
        "role=owner transfers ownership; use it only when the user explicitly wants ownership transfer, not merely edit access",
      ],
      sideEffect: "may change Drive file access or create an approval-governed Drive action",
      safety: "the exact permission id, grantee context, and new role must be clear",
    }),
    inputSchema: googleDrivePermissionUpdateInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.permission.update",
  }),
  defineWriteTool({
    name: "google_drive_permission_delete",
    pluginId: GOOGLE_DRIVE_PLUGIN_ID,
    label: "Delete Drive permission",
    description: writeToolDescription({
      useWhen: "the user wants to remove a Google Drive permission",
      operation: "Deletes one Drive permission",
      returns: `the ${toolOutputProperty(googleDriveExternalWriteOutputSchema, "write")} lifecycle status and safe failure details`,
      sideEffect: "may revoke Drive file access or create an approval-governed Drive action",
      safety: "the exact file and permission id must be confirmed because access can be revoked",
    }),
    inputSchema: googleDrivePermissionDeleteInputSchema,
    outputSchema: googleDriveExternalWriteOutputSchema,
    externalAction: "google_drive.permission.delete",
  }),
] as const satisfies readonly ToolContract[];

export type GoogleDriveToolName = (typeof googleDriveToolContracts)[number]["name"];
