// GENERATED: run npm run db -- types. Do not edit by hand.
// Source: packages/control-plane-contracts/src/database.types.ts
// Purpose: intermediate row interfaces for ts-to-zod schema generation.
// App code should use database.types.ts, TableRow<...>, or curated schemas.ts exports instead.
import { z } from "zod";
import { type DatabaseGeneratedJson } from "./database-row-types.generated";

export const databaseGeneratedJsonSchema: z.ZodSchema<DatabaseGeneratedJson> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), databaseGeneratedJsonSchema),
      z.array(databaseGeneratedJsonSchema),
    ])
    .nullable(),
);

export const profileActionGeneratedRowSchema = z.object({
  action_type: z.string(),
  created_at: z.string(),
  decided_at: z.string().nullable(),
  decided_by_channel_id: z.string().nullable(),
  decided_by_user_id: z.string().nullable(),
  decision: z.string().nullable(),
  decision_expected_request_hash: z.string().nullable(),
  decision_metadata: databaseGeneratedJsonSchema,
  decision_source: z.string().nullable(),
  equivalent_action_key: z.string().nullable(),
  execution_payload: databaseGeneratedJsonSchema,
  expires_at: z.string().nullable(),
  id: z.string(),
  idempotency_key: z.string(),
  origin_channel_provider: z.string().nullable(),
  origin_profile_channel_id: z.string().nullable(),
  origin_sender_id: z.string().nullable(),
  origin_session_id: z.string().nullable(),
  origin_session_key: z.string().nullable(),
  profile_id: z.string(),
  provider_error: databaseGeneratedJsonSchema.nullable(),
  provider_execution_attempts: z.number(),
  provider_execution_finished_at: z.string().nullable(),
  provider_execution_started_at: z.string().nullable(),
  provider_execution_status: z.string(),
  provider_idempotency_key: z.string(),
  request_hash: z.string(),
  requester_assistant_id: z.string().nullable(),
  result_payload: databaseGeneratedJsonSchema.nullable(),
  review_payload: databaseGeneratedJsonSchema,
  risk_level: z.string(),
  status: z.string(),
  summary: z.string(),
  target_id: z.string().nullable(),
  title: z.string(),
  tool_call_id: z.string().nullable(),
  tool_name: z.string(),
  updated_at: z.string(),
});

export const profileProposalGeneratedRowSchema = z.object({
  blocker_code: z.string().nullable(),
  blocker_summary: z.string().nullable(),
  converted_profile_action_id: z.string().nullable(),
  created_at: z.string(),
  decided_at: z.string().nullable(),
  decided_by_user_id: z.string().nullable(),
  decision: z.string().nullable(),
  decision_source: z.string().nullable(),
  equivalence_key: z.string(),
  evidence: databaseGeneratedJsonSchema,
  expires_at: z.string().nullable(),
  id: z.string(),
  profile_id: z.string(),
  proposal_kind: z.string(),
  proposal_payload: databaseGeneratedJsonSchema,
  review_payload: databaseGeneratedJsonSchema,
  revision: z.number(),
  source_scheduled_task_id: z.string().nullable(),
  source_work_item_id: z.string().nullable(),
  status: z.string(),
  summary: z.string(),
  superseded_by_proposal_id: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const browserAuthContextGeneratedRowSchema = z.object({
  account_hint: z.string().nullable(),
  allowed_domains: z.array(z.string()),
  browserbase_context_id: z.string(),
  created_at: z.string(),
  deleted_at: z.string().nullable(),
  id: z.string(),
  label: z.string(),
  last_verified_at: z.string().nullable(),
  primary_domain: z.string(),
  profile_id: z.string(),
  status: z.string(),
  updated_at: z.string(),
});

export const browserTaskGeneratedRowSchema = z.object({
  assigned_assistant_id: z.string().nullable(),
  cancel_requested_at: z.string().nullable(),
  created_at: z.string(),
  dedupe_key: z.string(),
  ended_at: z.string().nullable(),
  goal: z.string(),
  id: z.string(),
  mode: z.string(),
  note: z.string().nullable(),
  profile_id: z.string(),
  result: databaseGeneratedJsonSchema.nullable(),
  revision: z.number(),
  state: databaseGeneratedJsonSchema,
  status: z.string(),
  summary: z.string().nullable(),
  updated_at: z.string(),
  wait: databaseGeneratedJsonSchema.nullable(),
});

export const browserTaskEventGeneratedRowSchema = z.object({
  actor_id: z.string().nullable(),
  actor_type: z.string(),
  browser_task_id: z.string(),
  created_at: z.string(),
  event_type: z.string(),
  id: z.string(),
  payload: databaseGeneratedJsonSchema,
});

export const browserHandoffGeneratedRowSchema = z.object({
  browser_auth_context_id: z.string().nullable(),
  browser_task_id: z.string(),
  browserbase_session_id: z.string(),
  cancelled_at: z.string().nullable(),
  client_url: z.string(),
  completed_at: z.string().nullable(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  profile_id: z.string(),
  reason: z.string(),
  status: z.string(),
  updated_at: z.string(),
});

export const approvalPolicyGeneratedRowSchema = z.object({
  created_at: z.string(),
  id: z.string(),
  profile_id: z.string(),
  rules: databaseGeneratedJsonSchema,
  updated_at: z.string(),
});

export const profileAssistantWorkRouteGeneratedRowSchema = z.object({
  config: databaseGeneratedJsonSchema,
  connected_provider_account_id: z.string().nullable(),
  created_at: z.string(),
  event_type: z.string(),
  id: z.string(),
  managed_by: z.string(),
  profile_id: z.string(),
  updated_at: z.string(),
});

export const artifactGeneratedRowSchema = z.object({
  artifact_type: z.string(),
  browser_task_id: z.string().nullable(),
  byte_size: z.number().nullable(),
  created_at: z.string(),
  description: z.string().nullable(),
  filename: z.string(),
  id: z.string(),
  idempotency_key: z.string().nullable(),
  metadata: databaseGeneratedJsonSchema,
  mime_type: z.string().nullable(),
  profile_action_id: z.string().nullable(),
  profile_id: z.string(),
  sha256: z.string().nullable(),
  storage_bucket: z.string(),
  storage_key: z.string(),
});

export const agentRunGeneratedRowSchema = z.object({
  agent_id: z.string().nullable(),
  created_at: z.string(),
  ended_at: z.string().nullable(),
  failure: databaseGeneratedJsonSchema.nullable(),
  id: z.string(),
  profile_id: z.string(),
  runtime_run_id: z.string().nullable(),
  session_id: z.string().nullable(),
  session_key: z.string().nullable(),
  started_at: z.string(),
  status: z.string(),
  updated_at: z.string(),
});

export const agentEventGeneratedRowSchema = z.object({
  agent_run_id: z.string().nullable(),
  created_at: z.string(),
  event_type: z.string(),
  id: z.string(),
  occurred_at: z.string(),
  payload: databaseGeneratedJsonSchema,
  profile_id: z.string(),
  source: z.string(),
  source_event_key: z.string().nullable(),
  visibility: z.string(),
});

export const assistantGeneratedRowSchema = z.object({
  assistant_id: z.string(),
  created_at: z.string(),
  profile_id: z.string(),
  updated_at: z.string(),
});

export const backendJobGeneratedRowSchema = z.object({
  attempts: z.number(),
  capability_account_link_id: z.string().nullable(),
  created_at: z.string(),
  dedupe_key: z.string().nullable(),
  finished_at: z.string().nullable(),
  id: z.string(),
  kind: z.string(),
  last_error: z.string().nullable(),
  lease_expires_at: z.string().nullable(),
  leased_by: z.string().nullable(),
  max_attempts: z.number(),
  origin_agent_id: z.string().nullable(),
  origin_session_id: z.string().nullable(),
  origin_session_key: z.string().nullable(),
  origin_tool_call_id: z.string().nullable(),
  payload: databaseGeneratedJsonSchema,
  priority: z.number(),
  profile_id: z.string(),
  run_after: z.string(),
  started_at: z.string().nullable(),
  status: z.string(),
  updated_at: z.string(),
});

export const profileLearningReviewRunGeneratedRowSchema = z.object({
  context_window_end_at: z.string(),
  context_window_start_at: z.string(),
  created_at: z.string(),
  error_code: z.string().nullable(),
  error_message: z.string().nullable(),
  finished_at: z.string().nullable(),
  id: z.string(),
  local_date: z.string().nullable(),
  metadata: databaseGeneratedJsonSchema,
  model: z.string(),
  processed_source_end_at: z.string().nullable(),
  profile_id: z.string(),
  review_mode: z.string(),
  source_window_end_at: z.string(),
  source_window_start_at: z.string(),
  started_at: z.string(),
  status: z.string(),
  summary: z.string().nullable(),
  updated_at: z.string(),
  window_end_at: z.string(),
  window_start_at: z.string(),
});

export const profileLearningReviewCursorGeneratedRowSchema = z.object({
  created_at: z.string(),
  last_successful_run_id: z.string().nullable(),
  metadata: databaseGeneratedJsonSchema,
  processed_through_at: z.string(),
  profile_id: z.string(),
  updated_at: z.string(),
});

export const profileLearningReviewObservationGeneratedRowSchema = z.object({
  confidence: z.string(),
  created_at: z.string(),
  evidence: databaseGeneratedJsonSchema,
  id: z.string(),
  missing_context: z.string().nullable(),
  observation_type: z.string(),
  profile_id: z.string(),
  run_id: z.string(),
  statement: z.string(),
  target_id: z.string().nullable(),
  target_kind: z.string(),
  updated_at: z.string(),
});

export const profileLearningReviewCandidateGeneratedRowSchema = z.object({
  applied_at: z.string().nullable(),
  applied_reference: databaseGeneratedJsonSchema,
  candidate_type: z.string(),
  confidence: z.string(),
  created_at: z.string(),
  evidence: databaseGeneratedJsonSchema,
  failure_message: z.string().nullable(),
  id: z.string(),
  profile_id: z.string(),
  proposed_patch: databaseGeneratedJsonSchema,
  rationale: z.string(),
  run_id: z.string(),
  status: z.string(),
  target_id: z.string().nullable(),
  target_kind: z.string(),
  updated_at: z.string(),
});

export const profileGuidanceGeneratedRowSchema = z.object({
  body_markdown: z.string(),
  created_at: z.string(),
  id: z.string(),
  key: z.string(),
  profile_id: z.string(),
  revision: z.number(),
  selector_description: z.string(),
  status: z.string(),
  title: z.string(),
  updated_at: z.string(),
});

export const assistantScheduledTaskGeneratedRowSchema = z.object({
  created_at: z.string(),
  created_by_agent_id: z.string().nullable(),
  created_by_session_id: z.string().nullable(),
  created_by_session_key: z.string().nullable(),
  created_by_tool_call_id: z.string().nullable(),
  dedupe_key: z.string().nullable(),
  id: z.string(),
  instructions: z.string(),
  last_run_at: z.string().nullable(),
  next_run_at: z.string().nullable(),
  profile_id: z.string(),
  revision: z.number(),
  schedule: databaseGeneratedJsonSchema,
  status: z.string(),
  target: databaseGeneratedJsonSchema,
  timezone: z.string().nullable(),
  title: z.string(),
  updated_at: z.string(),
});

export const assistantWorkItemGeneratedRowSchema = z.object({
  attempts: z.number(),
  available_at: z.string(),
  claim_expires_at: z.string().nullable(),
  claim_token: z.string().nullable(),
  claimed_at: z.string().nullable(),
  claimed_by_agent_id: z.string().nullable(),
  claimed_by_session_key: z.string().nullable(),
  created_at: z.string(),
  dedupe_key: z.string().nullable(),
  finished_at: z.string().nullable(),
  id: z.string(),
  kind: z.string(),
  last_error: z.string().nullable(),
  max_attempts: z.number(),
  origin_agent_id: z.string().nullable(),
  origin_scheduled_task_id: z.string().nullable(),
  origin_session_id: z.string().nullable(),
  origin_session_key: z.string().nullable(),
  origin_tool_call_id: z.string().nullable(),
  payload: databaseGeneratedJsonSchema,
  priority: z.number(),
  profile_id: z.string(),
  result: databaseGeneratedJsonSchema.nullable(),
  status: z.string(),
  updated_at: z.string(),
});

export const providerWebhookSubscriptionGeneratedRowSchema = z.object({
  adapter_key: z.string(),
  capability_account_link_id: z.string(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  cursor: databaseGeneratedJsonSchema,
  event_scope: z.string(),
  expires_at: z.string().nullable(),
  external_subscription_id: z.string().nullable(),
  id: z.string(),
  last_error_code: z.string().nullable(),
  last_error_message: z.string().nullable(),
  last_notification_at: z.string().nullable(),
  last_success_at: z.string().nullable(),
  next_reconcile_at: z.string().nullable(),
  profile_id: z.string(),
  provider_key: z.string(),
  provider_state: databaseGeneratedJsonSchema,
  resource_id: z.string(),
  resource_type: z.string(),
  status: z.string(),
  updated_at: z.string(),
});

export const providerFileStateGeneratedRowSchema = z.object({
  capability_account_link_id: z.string(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  ctag: z.string().nullable(),
  deleted_at: z.string().nullable(),
  etag: z.string().nullable(),
  external_file_id: z.string(),
  id: z.string(),
  last_modified_at: z.string().nullable(),
  metadata: databaseGeneratedJsonSchema,
  mime_type: z.string().nullable(),
  name: z.string().nullable(),
  parent_reference: databaseGeneratedJsonSchema,
  profile_id: z.string(),
  provider_key: z.string(),
  resource_id: z.string(),
  resource_type: z.string(),
  updated_at: z.string(),
  web_url: z.string().nullable(),
});

export const providerSandboxResourceGeneratedRowSchema = z.object({
  capability_account_link_id: z.string(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  metadata: databaseGeneratedJsonSchema,
  profile_id: z.string(),
  provider_key: z.string(),
  resource_id: z.string(),
  resource_type: z.string(),
  state: databaseGeneratedJsonSchema,
  updated_at: z.string(),
});

export const providerSandboxRequestGeneratedRowSchema = z.object({
  capability_account_link_id: z.string(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  error: databaseGeneratedJsonSchema.nullable(),
  id: z.string(),
  metadata: databaseGeneratedJsonSchema,
  operation: z.string(),
  profile_id: z.string(),
  provider_key: z.string(),
  request: databaseGeneratedJsonSchema,
  resource_id: z.string().nullable(),
  resource_type: z.string().nullable(),
  response: databaseGeneratedJsonSchema,
  status: z.string(),
  updated_at: z.string(),
});

export const providerWebhookDeliveryGeneratedRowSchema = z.object({
  adapter_key: z.string(),
  authenticated: z.boolean(),
  backend_job_id: z.string().nullable(),
  created_at: z.string(),
  delivery_key: z.string(),
  error_code: z.string().nullable(),
  error_message: z.string().nullable(),
  id: z.string(),
  payload: databaseGeneratedJsonSchema,
  payload_hash: z.string(),
  processed_at: z.string().nullable(),
  provider_key: z.string(),
  received_at: z.string(),
  request_headers: databaseGeneratedJsonSchema,
  status: z.string(),
  subscription_id: z.string().nullable(),
  updated_at: z.string(),
});

export const profilePortalLaunchIntentGeneratedRowSchema = z.object({
  consumed_at: z.string().nullable(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  intent_payload: databaseGeneratedJsonSchema,
  intent_type: z.string(),
  origin_agent_id: z.string().nullable(),
  origin_session_id: z.string().nullable(),
  origin_session_key: z.string().nullable(),
  origin_tool_call_id: z.string().nullable(),
  profile_id: z.string(),
  section: z.string(),
  slug: z.string(),
  status: z.string(),
  surface: z.string(),
});

export const providerWriteReceiptGeneratedRowSchema = z.object({
  capability_account_link_id: z.string(),
  capability_slug: z.string(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  external_resource_id: z.string(),
  external_resource_type: z.string(),
  finished_at: z.string(),
  id: z.string(),
  metadata: databaseGeneratedJsonSchema,
  operation: z.string(),
  profile_action_id: z.string(),
  profile_id: z.string(),
  provider_key: z.string(),
  started_at: z.string(),
  tool_name: z.string(),
});

export const boldSignDocumentGeneratedRowSchema = z.object({
  capability_account_link_id: z.string(),
  completed_at: z.string().nullable(),
  connected_provider_account_id: z.string(),
  created_at: z.string(),
  document_id: z.string(),
  id: z.string(),
  ownership_status: z.string(),
  profile_id: z.string(),
  provider_account_id: z.string(),
  provider_metadata: databaseGeneratedJsonSchema,
  provider_status: z.string().nullable(),
  sent_at: z.string().nullable(),
  signer_email: z.string().nullable(),
  source: z.string(),
  title: z.string().nullable(),
  updated_at: z.string(),
});

export const connectedProviderAccountGeneratedRowSchema = z.object({
  account_email: z.string().nullable(),
  connected_at: z.string().nullable(),
  connection_status: z.string(),
  created_at: z.string(),
  credential_kind: z.string(),
  credential_status: z.string().nullable(),
  display_label: z.string().nullable(),
  id: z.string(),
  last_error: z.string().nullable(),
  metadata: databaseGeneratedJsonSchema,
  nango_connection_id: z.string().nullable(),
  nango_provider_config_key: z.string().nullable(),
  profile_id: z.string(),
  provider: z.string(),
  provider_account_id: z.string(),
  scopes: databaseGeneratedJsonSchema,
  updated_at: z.string(),
});

export const phoneCallAttemptGeneratedRowSchema = z.object({
  answered_at: z.string().nullable(),
  call_brief_hash: z.string(),
  call_id: z.string(),
  country: z.string(),
  created_at: z.string(),
  current_turn_token_hash: z.string().nullable(),
  duration_seconds: z.number().nullable(),
  ended_at: z.string().nullable(),
  failure_kind: z.string().nullable(),
  failure_message: z.string().nullable(),
  from_phone_e164: z.string().nullable(),
  hold_timeout_seconds: z.number(),
  id: z.string(),
  last_provider_event_at: z.string().nullable(),
  last_transcript_at: z.string().nullable(),
  max_duration_seconds: z.number(),
  opening_line: z.string(),
  pre_connect_dtmf_hash: z.string().nullable(),
  profile_action_id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  provider_call_sid: z.string().nullable(),
  provider_parent_call_sid: z.string().nullable(),
  provider_status: z.string().nullable(),
  provider_status_updated_at: z.string().nullable(),
  purpose: z.string(),
  started_at: z.string().nullable(),
  status: z.string(),
  summary: z.string().nullable(),
  terminal_reason: z.string().nullable(),
  to_phone_e164: z.string(),
  turn_index: z.number(),
  updated_at: z.string(),
  verified_phone_source_url: z.string(),
});

export const phoneCallEventGeneratedRowSchema = z.object({
  call_id: z.string(),
  created_at: z.string(),
  dedupe_key: z.string(),
  event_kind: z.string(),
  id: z.string(),
  occurred_at: z.string(),
  phone_call_attempt_id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  provider_call_sid: z.string().nullable(),
  provider_event_id: z.string().nullable(),
  provider_payload: databaseGeneratedJsonSchema,
  turn_index: z.number().nullable(),
  turn_token_hash: z.string().nullable(),
});

export const phoneCallTranscriptEntryGeneratedRowSchema = z.object({
  call_id: z.string(),
  created_at: z.string(),
  id: z.string(),
  occurred_at: z.string(),
  phone_call_attempt_id: z.string(),
  profile_id: z.string(),
  provider_event_id: z.string().nullable(),
  speaker: z.string(),
  text: z.string(),
  turn_index: z.number(),
});

export const phoneSmsAttemptGeneratedRowSchema = z.object({
  body_hash: z.string(),
  body_preview: z.string(),
  country: z.string(),
  created_at: z.string(),
  delivered_at: z.string().nullable(),
  destination_evidence: databaseGeneratedJsonSchema,
  destination_evidence_kind: z.string(),
  failure_kind: z.string().nullable(),
  failure_message: z.string().nullable(),
  from_phone_e164: z.string().nullable(),
  id: z.string(),
  profile_action_id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  provider_message_sid: z.string().nullable(),
  provider_status: z.string().nullable(),
  provider_status_updated_at: z.string().nullable(),
  purpose: z.string(),
  related_call_attempt_id: z.string().nullable(),
  reply_to_message_sid: z.string().nullable(),
  sent_at: z.string().nullable(),
  status: z.string(),
  to_phone_e164: z.string(),
  updated_at: z.string(),
  verified_phone_source_label: z.string().nullable(),
  verified_phone_source_url: z.string().nullable(),
});

export const phoneSmsEventGeneratedRowSchema = z.object({
  created_at: z.string(),
  dedupe_key: z.string(),
  event_kind: z.string(),
  id: z.string(),
  occurred_at: z.string(),
  phone_sms_attempt_id: z.string().nullable(),
  profile_id: z.string(),
  provider: z.string(),
  provider_message_sid: z.string().nullable(),
  provider_payload: databaseGeneratedJsonSchema,
});

export const phoneInboundSmsMessageGeneratedRowSchema = z.object({
  body_text: z.string(),
  capability_account_link_id: z.string(),
  created_at: z.string(),
  dedupe_key: z.string(),
  delivery_id: z.string().nullable(),
  from_phone_e164: z.string(),
  id: z.string(),
  media_count: z.number(),
  message_sid: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  received_at: z.string(),
  to_phone_e164: z.string(),
  work_item_id: z.string().nullable(),
});

export const capabilityAccountLinkGeneratedRowSchema = z.object({
  capability_slug: z.string(),
  config: databaseGeneratedJsonSchema,
  connected_provider_account_id: z.string().nullable(),
  created_at: z.string(),
  id: z.string(),
  is_default: z.boolean(),
  label: z.string(),
  profile_capability_id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  readiness_blocker_code: z.string().nullable(),
  readiness_last_error: z.string().nullable(),
  readiness_last_success_at: z.string().nullable(),
  readiness_latest_backend_job_id: z.string().nullable(),
  readiness_metadata: databaseGeneratedJsonSchema,
  readiness_status: z.string(),
  required: z.boolean(),
  status: z.string(),
  updated_at: z.string(),
});

export const providerConnectIntentGeneratedRowSchema = z.object({
  capability_account_link_id: z.string().nullable(),
  capability_slug: z.string(),
  connected_provider_account_id: z.string().nullable(),
  created_at: z.string(),
  expires_at: z.string(),
  id: z.string(),
  profile_capability_id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  requested_label: z.string().nullable(),
  status: z.string(),
  updated_at: z.string(),
});

export const profileCapabilityGeneratedRowSchema = z.object({
  capability_slug: z.string(),
  config: databaseGeneratedJsonSchema,
  created_at: z.string(),
  id: z.string(),
  profile_id: z.string(),
  required: z.boolean(),
  status: z.string(),
  updated_at: z.string(),
});

export const profileChannelGeneratedRowSchema = z.object({
  created_at: z.string(),
  delivery_config: databaseGeneratedJsonSchema,
  external_identity: z.string(),
  id: z.string(),
  profile_id: z.string(),
  provider: z.string(),
  status: z.string(),
  updated_at: z.string(),
});

export const profileGeneratedRowSchema = z.object({
  created_at: z.string(),
  display_name: z.string(),
  id: z.string(),
  metadata: databaseGeneratedJsonSchema,
  preferences: databaseGeneratedJsonSchema,
  status: z.string(),
  timezone: z.string(),
  updated_at: z.string(),
  user_id: z.string(),
});
